services:
  - type: web
    name: be-zmest-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health

